### ISSUE TITLE
"Parse error" Android 10, Huawei mate 30 pro

### ISSUE THREAD

**Issue by ZAMinationRU** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#108]
I download android apk but when i try instail it they saying "parse error"
Emui 12
![Screenshot_20240915_195758](https://github.com/user-attachments/assets/b8952423-caeb-4f4b-8a43-105925913826)

**Comment by SineVector241** [comment]
VoiceCraft only supports android 12+

**Comment by SineVector241** [comment]
Specified by this line:
https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/blob/master/VoiceCraft.Maui/VoiceCraft.Maui.csproj#L36
https://developer.android.com/tools/releases/platforms#11

**Comment by SineVector241** [comment]
https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/blob/dev/VoiceCraft.Client%2FVoiceCraft.Client.Android%2FVoiceCraft.Client.Android.csproj#L5
