### ISSUE TITLE
connect button don't work

### ISSUE THREAD

**Issue by kilivan4iK** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#13]
I did everything like in the video but the connect button does not work
![зображення](https://user-images.githubusercontent.com/74571110/209562656-93dfba05-e7b6-46b9-93c9-5e0b4faa6d99.png)

**Comment by SineVector241** [comment]
Maybe try setting the port on a higher number? E.g. 6567

**Comment by kilivan4iK** [comment]
Yes, that helped, thank you.
