### ISSUE TITLE
Is it possible to make a plugin for BDS?

### ISSUE THREAD

**Issue by kilivan4iK** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#14]
Is it possible to make an automatic connection to BDS and execute commands via/using the BDSLiteLoader plugin?
And also can you make an injector like in Horion and Onix Client to be able to control VoiceCraft directly in Minecraft?

https://github.com/LiteLDev/LiteLoaderBDS
https://www.litebds.com/home/

**Comment by SineVector241** [comment]
I have not learnt C++ or reverse engineering so figuring all of that out will take me at least 2-3 years. However it is entirely possible to make all of though I do not know if direct VC through DLL in mc is possible

**Comment by kilivan4iK** [comment]
BDSLiteLoader support C++, JavaScript(NodeJs), Lua, .NET
