### ISSUE TITLE
!Vclink

### ISSUE THREAD

**Issue by Mr-Mr-Minecraft** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#22]
when I do !vclink nothing happens i have checked and everything is perfect please help!

**Comment by SineVector241** [comment]
![Screenshot_2023-04-25-08-05-06-32_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/69619913/234126751-e2dadc6f-2e24-4942-9675-6991b92240ec.jpg)

**Comment by Mr-Mr-Minecraft** [comment]
What is this?
![Screenshot 2023-04-24 184601](https://user-images.githubusercontent.com/131720229/234132375-5a14d6b7-7f35-4b39-9746-08f3391e7230.png)

**Comment by Mr-Mr-Minecraft** [comment]
now it is also not letting me join

**Comment by SineVector241** [comment]
You've messed up your permissions.json. Send me the contents of it and ill fix it

**Comment by Mr-Mr-Minecraft** [comment]
ok

**Comment by Mr-Mr-Minecraft** [comment]
Should i send you the whole folder

**Comment by SineVector241** [comment]
Just the file

**Comment by Mr-Mr-Minecraft** [comment]
ok i doesnt let me what is your discord?

**Comment by SineVector241** [comment]
Look on my yt channel. 2 discords u can join that I am in.

**Comment by Mr-Mr-Minecraft** [comment]
ok

**Comment by Mr-Mr-Minecraft** [comment]
Ok I am in the server my name is BigBoyOtter
