### ISSUE TITLE
Donate for you? =)

### ISSUE THREAD

**Issue by sircurse** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#31]
Hi SineVector, I just tested your application, and it is really powerful, congratulations for the well done job, I m not a developer so if you have any donate process let me know, I will be more than happy to pay you a pizza.

Btw... By any chance to have a Linux version of the server? Paying a license to Microsoft nowadays is not one of my interests =)

**Comment by SineVector241** [comment]
Currently I do not have a donation payment method setup but I may open up one later. Also linux I don't think is exactly supported just yet. Although however if you are able to download .NET Framework drivers on Linux then you may be able to run the server.

**Comment by ModMaker101** [comment]
You should use paypal

**Comment by SineVector241** [comment]
Opened
https://ko-fi.com/sinevector241
