### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by ModMaker101** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#37]
The addon has the module for the server 1.2.0-beta when it needs to be 1.4.0-beta and the server-ui module needs to be 1.1.0-beta and the server-net is fine.

**Comment by ModMaker101** [comment]
sorry you need to update the release 1.3.5 because you have the wrong addon

**Comment by ModMaker101** [comment]
also what is your discord if you have one

**Comment by SineVector241** [comment]
> sorry you need to update the release 1.3.5 because you have the wrong addon

https://github.com/SineVector241/VoiceCraft-MCBE_ProximityChat_Addon/releases/tag/v1.3.5-alpha_1.20

**Comment by SineVector241** [comment]
> the 1.4.0 ui is a lot better can't wait till you release it to the public and when are you going to release it

soon. Probably after a video

**Comment by ModMaker101** [comment]
I am using the 1.4.0 for my server am I allowed to if not then I will switch.

**Comment by SineVector241** [comment]
Thats fine. Just be warned its untested and may contain a lot of bugs.

**Comment by ModMaker101** [comment]
okey

**Comment by ModMaker101** [comment]
is this an error you been having

**Comment by SineVector241** [comment]
did you enable the module at all?

**Comment by ModMaker101** [comment]
yes

**Comment by ModMaker101** [comment]
but I resolved it
