### ISSUE TITLE
feat: Discord like overlay

### ISSUE THREAD

**Issue by UnknownNull** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#42]
Add a popup for voice and microphone connection like discord. For app

**Comment by SineVector241** [comment]
Could you explain in more detail and show pictures if possible?

**Comment by UnknownNull** [comment]
It's strange that you haven't experienced Discord yet.

The pop-up opens and closes with one click. When it opens, you can mute or unmute your voice and see 3 additional people who are in the voice, and when you close the pop-up, only an icon of the last person who spoke will remain.

![10](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/91208232/f8f47f6e-c65f-4f3c-b3aa-38a08f7f7639)
More: https://www.google.com/search?q=discord+popup+voice+overlay&client=ms-android-samsung-rev2&hl=fa&prmd=vibn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiM0Ime4IeAAxWfg_0HHTzXC58Q_AUICygC&biw=412&bih=736&dpr=2.63#imgrc=nCQE3hOvwBRKQM

**Comment by SineVector241** [comment]
Oh. Thats called an overlay. I may add it but it is difficult and certain backwards compatibility will be difficult to implement for that
