### ISSUE TITLE
Panel for server administrators 

### ISSUE THREAD

**Issue by UnknownNull** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#43]
Addition of a management panel for server administrators to monitor the servers

**Comment by CreeperG16** [comment]
The server console has a few commands to kick/ban/mute clients

**Comment by UnknownNull** [comment]
I mean monitoring, that is, connect to any number of players grouped close to each other who are connected in the graphical panel that the administrator has and monitor their conversation so that, for example, the rules of the server are not violated.

**Comment by SineVector241** [comment]
That's literally the same as going in spectator and TPing to that group of players. I won't be adding this myself but the code is all there to add it yourself and PR if you want to.
