### ISSUE TITLE
Can't contact server.

### ISSUE THREAD

**Issue by GreenChristo819** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#45]
When I first went onto the server, I input the localhost IP address, the port and the key after the !connect. The response said "couldn't contact server". I was watching the video and I'm pretty sure I did everything correctly.

**Comment by SineVector241** [comment]
Is the VoiceCraft server running on the same machine?

**Comment by GreenChristo819** [comment]
Yes it is.

**Comment by SineVector241** [comment]
Is the port correct. Remember its the MCCOMM Port

**Comment by GreenChristo819** [comment]
Yes. 9050.

**Comment by SineVector241** [comment]
Odd. I was able to get it to work a few hours ago.

**Comment by SineVector241** [comment]
Do you have the latest addon?
https://github.com/SineVector241/VoiceCraft-MCBE_ProximityChat_Addon/releases/tag/v1.4.0-alpha_1.20.10

**Comment by GreenChristo819** [comment]
I updated the pack, but it still doesn't work

**Comment by SineVector241** [comment]
Could you show a picture or a video of the steps you took?

**Comment by GreenChristo819** [comment]
Yes. Before I do, does the IP address need to be for the Minecraft server or the voice craft server?

**Comment by GreenChristo819** [comment]
Sure. Before I do, my server is hosted through Sternos, first, does the addon work with it (I know the addon file itself does). Second, do I need the Sternos IP address, or the local IP where the VoiceCraft server is hosted?

**Comment by SineVector241** [comment]
I have no idea if the addon will work with Aternos. Second you need to know the VoiceCraft's local ip instead

**Comment by GreenChristo819** [comment]
![Screenshot 2023-07-14 184328](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/107236280/25a3c20a-c065-46eb-a4e8-a4d4276d335a)
![Screenshot 2023-07-14 184346](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/107236280/a74c2f35-b858-4971-b54e-0e6795ac3993)
![Screenshot 2023-07-14 200028](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/107236280/d69a2a8f-149e-4f47-b751-5308fa018d73)
![Screenshot 2023-07-14 200057](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/107236280/34742cf2-b6dd-4b32-9032-1bec9f2691a4)
![Screenshot 2023-07-14 200138](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/107236280/727a633f-4f5a-4be6-967a-6e30b2228a5b)

**Comment by SineVector241** [comment]
Yeh. Localhost IP will not work with the setup you have. The aternos server is hosted on a different machine so if you're hosting the VoiceCraft server on your computer you need to get the IP of your computer and port forward the MCCOMM port in order for connection to happen. This is explained in more detail in the wiki here
https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/wiki/Installing-the-Server

**Comment by GreenChristo819** [comment]
I tried, but it still won't connect.

**Comment by SineVector241** [comment]
Well 2 reasons.

A. You haven't port forwarded both on your router and or firewall.
B. You copied the wrong IP. There can be multiple different IP's displayed. Your public IP address is not the one you want. You want the local IP address which defines 
Internet -> Router -> Your Computer.

**Comment by GreenChristo819** [comment]
Ok. I think it's something with my server. Thanks for your help.
