### ISSUE TITLE
Would ever be an ARM release for Server software?

### ISSUE THREAD

**Issue by burakroket** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#46]
I'd like to use this software with my old phone (through Termux) and others probably like to use raspberry pi's to run since they are power efficient.

Edit: I wouldn't mind using wine but preferably a Linux release

**Comment by SineVector241** [comment]
You should be able to run the server on an arm architecture since the server isnt compiled to a specific architecture. You just need the drivers

**Comment by SineVector241** [comment]
You can download the arm drivers here.
https://dotnet.microsoft.com/en-us/download/dotnet/7.0

Make sure you download the ones under the title
`.NET Runtime 7.0.9`

**Comment by burakroket** [comment]
Should i install Linux version or windows version? Does wine recognize Linux drivers?

**Comment by SineVector241** [comment]
I don't think you need wine at all if you download the linux/arm drivers

**Comment by burakroket** [comment]
I managed to run server with linux dotnet version. No need for wine. Thank you for taking your time to help me. ![image](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/96832391/7cced426-1edf-49d7-8529-399834627b66)

**Comment by Neeedrose** [comment]
> I managed to run server with linux dotnet version. No need for wine. Thank you for taking your time to help me. ![image](https://private-user-images.githubusercontent.com/96832391/253795350-7cced426-1edf-49d7-8529-399834627b66.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NTI2MzIsIm5iZiI6MTcxODY1MjMzMiwicGF0aCI6Ii85NjgzMjM5MS8yNTM3OTUzNTAtN2NjZWQ0MjYtMWVkZi00OWQ3LTg1MjktMzk5ODM0NjI3YjY2LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxOTI1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NGVjNmM4YzFmOWY0MDI1OTQ5NWE2NDMzMTMzNTIyMDEzMzEyNTUyMGI5NGNhMGE3NzAwMjMwOGMyNjc4ZjQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jJWFuHwq5rC8uj0sibCfDzrQk030W-1kdkNkLB-8UCA)
> 
> Edit: I swiched to LinuxDeploy since I had root access for my phone.

Hey, I know this is a bit late but could you please show me how you have ran a .dll file on linux.

**Comment by burakroket** [comment]
Ok remembered how i did run. Im not an expert but it works :)

https://dotnet.microsoft.com/en-us/download/dotnet/8.0

download dotnet runtime from this page for your architecture. I'm on computer so i downloaded "x64".

![dotnet-runtime](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/96832391/67b08d30-787b-446e-abaf-79f1094d0e7b)

after downloading, extract it to folder. I named my folder "dotnet-8".

![dotnet-extract](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/96832391/4d319077-92bd-49cf-aa27-797e5f603606)

After that, put the "VoiceCraft" server in "dotnet-8" folder.

![dotnet-insideOfFolder](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/96832391/57106c4d-ae4a-4fe6-9382-9f72e9c4d0ea)

Run this command inside of "dotnet-8" folder:

`./dotnet VoiceCraft/VoiceCraft.Server.dll`

now it will run like this:

![server-running](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/96832391/97b05abe-41a4-4e35-b898-fee52c86fe2d)

**Comment by Miniontoby** [comment]
Hi everyone,

Public servers I like to run on a pterodactyl panel, so I decided to try and make myself an docker image (since pterodactyl uses docker images and because docker images can be used WITHOUT a pterodactyl panel).

So I have made a Dockerfile to download dotnet-8 and the server software and then added the CMD to run `dotnet VoiceCraft.Server.dll`. And I tested it, of course.

It is just a few lines of Dockerfile to make the image and it can be automated using github actions.

And for me to avoid having to write a complicated system to check if there is a new release here and then to build a new version, so I would rather want to add it here instead if the owner is oké with that.

I will make a PR for it if the owner want to support it and I will add the instructions for setting up the github actions secrets in there as well. But please tell me if you want to support Docker image as well!

**Comment by SineVector241** [comment]
Yes, I'd be happy to support a docker file on a separate repo though.

**Comment by Miniontoby** [comment]
Would you be able to add a github workflow here to trigger a workflow on my repo then?

I will join the discord to help you set it up if you are oké with that.

**Comment by SineVector241** [comment]
Yes, that's ok. Help would be appreciated since I am only maintaining this project until I'm done with another project.

**Comment by Miniontoby** [comment]
Docker images are now available!


- [At ghcr.io](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat_Docker/pkgs/container/voicecraft)
- And [at docker.io](https://hub.docker.com/r/sinevector241/voicecraft/tags)
