### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ModMaker101** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#49]
Can you make vcpc for docker

**Comment by SineVector241** [comment]
No idea how to do that. I don't use docker. But you can compile the code yourself.

**Comment by ModMaker101** [comment]
okey

**Comment by ModMaker101** [comment]
You should also look into doing Linux as some people can get it in some ways

**Comment by SineVector241** [comment]
> You should also look into doing Linux as some people can get it in some ways

https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/issues/46#issuecomment-1637032572

**Comment by ModMaker101** [comment]
nice
