### ISSUE TITLE
Directional hearing doesn't work

### ISSUE THREAD

**Issue by AndyFicile** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#53]

**Comment by SineVector241** [comment]
Did you enable the setting and have logged in with server sided positioning?

**Comment by AndyFicile** [comment]
> Did you enable the setting and have logged in with server sided positioning?

Yes, I did it. Sometimes I hear to the right when it's the opposite, and vice versa. I feel like it's random.

**Comment by SineVector241** [comment]
It is untested so I expected this to come up.

**Comment by AndyFicile** [comment]
> It is untested so I expected this to come up.

I just tried with client sided positioning and it doesn't work either.

**Comment by SineVector241** [comment]
> > It is untested so I expected this to come up.
> 
> I just tried with client sided positioning and it doesn't work either.

Of course it wont work on client sided positioning. I mentioned this in the wiki.

**Comment by SineVector241** [comment]
https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/commit/3ec287227ad5ecb01a5e1bec1dce8b63d9548839

**Comment by SineVector241** [comment]
fixed and tested https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/commit/f3ae0ca5767ddd6bb950fdc78ed7593be51896b7
