### ISSUE TITLE
how to install on ios

### ISSUE THREAD

**Issue by AFKmanYT** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#54]
.

**Comment by SineVector241** [comment]
IOS is not available

**Comment by ModMaker101** [comment]
Aren’t you working on the sine as you are using .net maui doesn’t it also compatible with ios

**Comment by SineVector241** [comment]
https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/wiki/FAQ#when-will-ios-port-of-voicecraft-be-available

**Comment by SineVector241** [comment]
Essentially. I am paywalled from porting to IOS

**Comment by ModMaker101** [comment]
I don’t like apple as they are greedy and don’t support anything
