### ISSUE TITLE
Microphone sensitivity (Mobile)

### ISSUE THREAD

**Issue by BaconedMoth** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#55]
Earlier today I was experiencing some issues with microphone sensitivity, I had to have my phone extremely close to my face for the voice craft application to even detect it and have others jear my voice. I had tested the app on two different devices and got the same issue. What can I do to fix this? Am I doing something wrong?

Both were connected on client side positioning on mobile

**Comment by SineVector241** [comment]
Thank you for the report.
It might be something to do with the automatic gain that android provides which is outputting a lower than expected volume. I'll be putting a DB detection slider that you can lower in order to increase microphone sensitivity

**Comment by SineVector241** [comment]
https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/commit/579999fa42b022bd6f9de9cdb776554ef2e5c4b4
