### ISSUE TITLE
setup for pocketmine

### ISSUE THREAD

**Issue by Errorforvirus** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#56]
hey sir how i can setup it in pocketmine?

**Comment by SineVector241** [comment]
https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/wiki/FAQ#can-you-make-it-pocketmine-compatible

**Comment by NeoNathoon** [comment]
It is pocket mine compatible we made it ;)

**Comment by SineVector241** [comment]
> It is pocket mine compatible we made it ;)

This version?
https://poggit.pmmp.io/p/VoiceCraft/1.0.0
