### ISSUE TITLE
how to activate addon on a server provider

### ISSUE THREAD

**Issue by EpicLucas17** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#57]
hello i want to activate the addon to be able to play with my friends but the addon is simply not activating i followed all the steps that were on the github wiki but it did not work could you help me how to do this

**Comment by SineVector241** [comment]
Did you enable beta api's on the world?

**Comment by EpicLucas17** [comment]
Yes

**Comment by EpicLucas17** [comment]
> Did you enable beta api's on the world?

Yes

**Comment by SineVector241** [comment]
Are there any content logging errors?

**Comment by EpicLucas17** [comment]
Yes

**Comment by EpicLucas17** [comment]
I'll take it for you to see

**Comment by EpicLucas17** [comment]
I'll send you tomorrow I thought I'd get it here but I'll send it tomorrow

**Comment by EpicLucas17** [comment]
I downloaded the files you left but it's still not running, I opened the voicecraft.server and this appeared here
![Captura de tela 2023-09-08 231951](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/142638342/515ede0e-167a-4b93-adb3-00a7f0c6ef74)

**Comment by EpicLucas17** [comment]
But no voice error appeared on the server I accessed the error logs and there are only other types of errors that come from the add-ons that I put on the server

**Comment by EpicLucas17** [comment]
the server that is hosted and the enxadahost
![image](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/142638342/973dac7f-8a02-444f-a10a-fac40fd76cf8)

**Comment by SineVector241** [comment]
> I downloaded the files you left but it's still not running, I opened the voicecraft.server and this appeared here
> ![Captura de tela 2023-09-08 231951](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/142638342/515ede0e-167a-4b93-adb3-00a7f0c6ef74)
> 

Run the command it asks on a command prompt/ windows terminal on the same device the voice craft server is running on to give it port access.

**Comment by EpicLucas17** [comment]
I managed to do this, but it didn't work out very well. I'll try to go through realms, I think it should be easier to configure
