### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by ModMaker101** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#60]
Do you want to help me make log files for the server side

**Comment by SineVector241** [comment]
it isn't that hard.. Just edit the Logger.cs file to write to a txt file.

**Comment by ModMaker101** [comment]
Ok

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SineVector241** [comment]
Implemented.

https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/commit/117b0b56e5336acc4731882218cc4eaf409eeb90
