### ISSUE TITLE
Simple Voice Chat mod compatibility for GeyserMC servers or unmodded java

### ISSUE THREAD

**Issue by FluffyCyanFox** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#74]
**Summary**
A java plugin in the form of an [addon](https://modrepo.de/minecraft/voicechat/addons) for Simple Voice Chat would function as a bridge to VoiceCraftProximityChat.
**Detailed Description**
[Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat) and VoiceCraftProximityChat are similar in scope and feature set. Bridging the two together would allow GeyserMC players to communicate with Java players without using the (very tedious and feature lacking) Discord bot method. Not only that, players who don't want to install a mod loader for java could just run this program instead. This would also allow better feature parity with Simple Voice Chat that is lost with the [Discord bridge plugin](https://modrinth.com/plugin/simple-voice-chat-discord-bridge).
**Additional Context**
Not really sure where the best place to have brought this up would've been. Simple Voice Chat actually has dedicated developers that work on addons/extensions for the base plugin and I think they could possibly be interested in collaborating on something like this. I'm also not sure how difficult this would be to pull off, while both projects use similar technologies it may be too much work to make this work, which is understandable. However, having cross-platform support for this would be a game changer. A _lot_ of people have been looking for a solution like this and would be interested in using this, whether that be for unmodded java or bedrock edition.

**Comment by SineVector241** [comment]
There is this which implements VoiceCraft for Java Geyser servers: https://github.com/mineserv-top/GeyserVoice, However implementing cross platform communication between Simple Voice Chat and VoiceCraft is quite difficult as they do both send and receive audio the same way but the audio compression and data is the other difficult thing.

**Comment by FluffyCyanFox** [comment]
Thanks so much for the fast response, I'll look into this! I didn't take into account the two platforms would be using different compression methods. Again, thanks a lot for pointing me in the right direction, been trying to find something like this for a long time.
