### ISSUE TITLE
Backward compatibility 

### ISSUE THREAD

**Issue by C0pperTux** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#77]
**Summary**
Is there anyway I can use the latest addon on Minecraft 1.20.30
**Detailed Description**
Is there any way I can use the latest addon and the lasted software for Minecraft 1.20.30 or am I limited to 1.20.60
**Add images if applicable**

**Additional Context**

**Comment by ModMaker101** [comment]
So downgrade the addon in the manifest.json

**Comment by ModMaker101** [comment]
Is what's he's saying

**Comment by C0pperTux** [comment]
Ok so do I have to learn a programming language or how do I do that

**Comment by SineVector241** [comment]
Not just the manifest, The code/functions for that version and the server modules.

**Comment by C0pperTux** [comment]
Is there a easy way to do that

**Comment by SineVector241** [comment]
Addon repo.
https://github.com/SineVector241/VoiceCraft-MCBE_ProximityChat_Addon

**Comment by ModMaker101** [comment]
I don't think you need to learn another programming language you just need to know what to change

**Comment by ModMaker101** [comment]
So you would need to change the script module version to the latest version in 1.20.30

**Comment by C0pperTux** [comment]
im trying to learn json

**Comment by C0pperTux** [comment]
i know c# only

**Comment by SineVector241** [comment]
Json isn't a programming language, It's a data format.

It works by having a key with a value.
E.g. 
`"T1":5`
The key T1 holds a value of 5.
