### ISSUE TITLE
there was a problem parsing the package

### ISSUE THREAD

**Issue by ASTRALLIBERTAD** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#89]
Hi SineVector241, I have a problem when I try to install the latest version of voicecraft  it says "there was a problem parsing the package". I'm currently running in Android 10.

Thanks in advance🙏🏻

**Comment by SineVector241** [comment]
Android 11+ is only supported.

**Comment by ASTRALLIBERTAD** [comment]
Thanks for responding SineVector241, can you give me some recommendations or alternatives to have proximity chat with my friends.

**Comment by SineVector241** [comment]
Not at the moment no.
