### ISSUE TITLE
Problem installing app for Android

### ISSUE THREAD

**Issue by OneEyeWarm** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#94]
**Describe the bug**
Failure on devices end to install app possibly because of files found in the latest APK zip fie
**To Reproduce**
1: Install zip file

2:unpack and install APK file using Package installer for Android

3:receive error

**Expected behavior**
An error will occur where the app was unable to install despite a variety of apps being used

**Screenshots**
If applicable, add screenshots to help explain your problem

**Platform (please complete the following information):**
 - OS: [android 10]
 - Version [e.g. v1.0.0]

**Additional context**
Very talented work btw good luck w college

**Comment by SineVector241** [comment]
Android 10 is not supported. Only android 11 or higher is supported

**Comment by Matthias-aa** [comment]
你好作者，在新的版本中可能会有向安卓十一往下的兼容吗，如果可以的话那万分感谢了，我是一个中国的BDS工作者，一个服主，我想在我的服务器中添加您的软件，这很厉害👍，期待新的版本中能兼容安卓10
