### ISSUE TITLE
Crash on Connect

### ISSUE THREAD

**Issue by deadeye12** [SineVector241/VoiceCraft-MCBE_Proximity_Chat#97]
**Describe the bug**
Client sees server on remote system. Ping at 20ms (local LAN) and MOTD shows up correctly. In client side position mode on both. I click connect and voicecraft clients pauses for a moment then crashes to desktop.

**Platform (please complete the following information):**
 - Version v1.0.5 release - however servers still says 1.0.4 in application

**Comment by SineVector241** [comment]
I believe this might be due to the fact that voicecraft is trying to resolve `localhost` on the DNS server which of course won't work. Did you try doing `127.0.0.1`?

**Comment by SineVector241** [comment]
also by crash, do you mean a fatal crash when the application just straight up closes? or does it just return to the server page.

**Comment by deadeye12** [comment]
Hi sineVector241 - thanks for your work on this.  It's a fatal crash to desktop (application closes, no other warnings or errors)   I have the server running on a separate machine on the LAN network,  Firewall, etc. configured on server machine.  I then installed the client application on a separate laptop.  I set both server and client to be client position mode. ("1" on server, and used the toggle in the client side app) I see my server from the client laptop, had ping, etc.  But once I click connect it fails to desktop.  I never the the chance to try and connect local minecraft to the local client.

**Comment by SineVector241** [comment]
Take a look through event viewer > Event Viewer (Local) > Windows Logs > Application. Then look for any error logs regarding voicecraft, that should tell you the crash log (refer to image)
![image](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/69619913/329822e0-8a98-42b5-a634-859ed1f3b651)

**Comment by deadeye12** [comment]
got it

Faulting application name: VoiceCraft.Maui.exe, version: 1.0.5.0, time stamp: 0x661f0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4597, time stamp: 0x7980d421
Exception code: 0xc000027b
Fault offset: 0x000000000012d352
Faulting process id: 0x116c
Faulting application start time: 0x01dacd0d8ac73b1c
Faulting application path: C:\Program Files\WindowsApps\com.sine.voicecraft.maui_1.0.5.0_x64__h5pv86t6mg52e\VoiceCraft.Maui.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4c63a100-a331-4000-885f-24028bdc41ab
Faulting package full name: com.sine.voicecraft.maui_1.0.5.0_x64__h5pv86t6mg52e
Faulting package-relative application ID: App

**Comment by SineVector241** [comment]
Odd. Never encountered that error before. Is that all of the EventData log?

**Comment by deadeye12** [comment]
Side note - installed client on same machine as server - was able to connect there and bind to local minecraft, so server side is behaving as expected.    On the remote system that crashes, before I try to connect, it shows there is 1 participant, so the remote client is communicating with the server in terms of signaling, but as soon as I hit connect the app crashes as before.  

Yes, this was in the details tab:

 VoiceCraft.Maui.exe 
   1.0.5.0 
   661f0000 
   KERNELBASE.dll 
   10.0.19041.4597 
   7980d421 
   c000027b 
   000000000012d352 
   2380 
   01dacd08400ad089 
   C:\Program Files\WindowsApps\com.sine.voicecraft.maui_1.0.5.0_x64__h5pv86t6mg52e\VoiceCraft.Maui.exe 
   C:\WINDOWS\System32\KERNELBASE.dll 
   fd3dd305-3ef2-4be9-9578-f13ec6d0f9ce 
   com.sine.voicecraft.maui_1.0.5.0_x64__h5pv86t6mg52e 
   App

**Comment by deadeye12** [comment]
worth mentioning this is an older (6yr) windows 10 laptop

**Comment by SineVector241** [comment]
Yeah I'm not sure what it is. It's something to do with the Kernal/OS so I'm not sure what's going.

**Comment by SineVector241** [comment]
Actually I think you copied the text in the general tab, go to Details > EventData. Upload a screenshot so I can see if you're in the correct tab.

**Comment by SineVector241** [comment]
actually nvm. That's correct, Yeah it's something to do with the kernal which I cannot decipher what's going on, might be something to do with low level WinAPI on the framework absolutely killing itself.

**Comment by deadeye12** [comment]
Agree, very strange. Tried running as admin just to see if it was a permissions things and no change
![image](https://github.com/SineVector241/VoiceCraft-MCBE_Proximity_Chat/assets/81756035/2c45846a-8eed-49b1-8021-00f7cdb54bea)

**Comment by SineVector241** [comment]
Yeah. No idea what's going on. What Windows Version do you have installed? Minimum supported by the application is compiled for windows10.0.19041.0

**Comment by deadeye12** [comment]
windows v. 19045.4598

**Comment by deadeye12** [comment]
Hey! Good news, if figured out the crash issue.  The laptop didn't have the C++ runtime distro installed!  I can now connect all around - however, neither us can hear each other at all so something still not right

**Comment by SineVector241** [comment]
Is voicecraft picking up audio? if so you should see a green highlight around the Disconnect, Deafen and Mute if it's picking up audio.

**Comment by deadeye12** [comment]
Yes, it is.  it shows green whenever I'm talking.  I also have a volume slider for the other player

**Comment by SineVector241** [comment]
did you try moving both players around? because when the MCWSS connection is established, the server doesn't receive any updates about player environments and positions if the player doesn't move.

**Comment by deadeye12** [comment]
Yes, we tried moving around to see if it would trigger position to no avail.  we can hear each others normal game play sounds, but no voice

**Comment by SineVector241** [comment]
try typing `list` in the voicecraft server console and check if both EnvironmentId's match

**Comment by deadeye12** [comment]
dang, I've broken something else b/c I can no longer connect minecraft to the local client. minecraft says connection failed.

**Comment by deadeye12** [comment]
no idea what I changed, but all is working now. Many thanks for all your help!
